name: Keep Streamlit App Alive

on:
  schedule:
    # Menjalankan ping setiap 8 jam sekali
    - cron: "0 */8 * * *"

  workflow_dispatch:

jobs:
  ping_app:
    runs-on: ubuntu-latest
    steps:
      - name: Ping URL Streamlit
        # Menggunakan cURL untuk mengakses URL aplikasi.
        run: curl -s -o /dev/null "https://konversi-nilai-mahasiswa.streamlit.app/"
